spring:
  profiles:
    active: local

  ##서버기동될때 자동 실행쿼리지정
#  datasource:
#    initialization-mode: always
#    platform: h2
#    data: data.sql

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  mvc:
    hiddenmethod:
      filter:

        # HTML <FORM>에서 th:method에서 PUT 또는 DELETE를 사용해서 보내는 _method를 사용해서  @PutMapping과 @DeleteMapping으로 요청을 맵핑.
        enabled: true

server:

  tomcat:
    # 톰캣 기본 요청 사이즈는 2MB 입니다. 그것보다 큰 요청을 받고 싶은 경우에 이 값을 조정해야 합니다.
    max-http-form-post-size: 5MB

  servlet:
    session:
      timeout: 30m

app:
  host: http://localhost:8080

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

#개발용
#  profiles: dev
#    datasource:
#      url: postgresql://localhost:5432/testdb
#      username: testuser
#      password: testpass
