spring:
  profiles:
    active: local

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

server:
  servlet:
    session:
      timeout: 30m