spring:
  profiles:
    active: dev

  ##서버기동될때 자동 실행쿼리지정
#  datasource:
#    initialization-mode: always
#    platform: h2
#    data: data.sql

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

server:

  tomcat:
    # 톰캣 기본 요청 사이즈는 2MB 입니다. 그것보다 큰 요청을 받고 싶은 경우에 이 값을 조정해야 합니다.
    max-http-form-post-size: 5MB

  servlet:
    session:
      timeout: 30m

app:
  host: http://localhost:8080

#개발용
#  profiles: dev
#    datasource:
#      url: postgresql://localhost:5432/testdb
#      username: testuser
#      password: testpass
